"""add stored_medianame in media_details table

Revision ID: 234dd525338f
Revises: 5282c6f66bde
Create Date: 2026-07-22 17:08:13.923613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234dd525338f'
down_revision: Union[str, Sequence[str], None] = '5282c6f66bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_details', sa.Column('stored_medianame', sa.String(), nullable=False))
    op.create_index(op.f('ix_media_details_stored_medianame'), 'media_details', ['stored_medianame'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_details_stored_medianame'), table_name='media_details')
    op.drop_column('media_details', 'stored_medianame')
    # ### end Alembic commands ###
