"""Add summary column to media detail table

Revision ID: 5282c6f66bde
Revises: c21465661c33
Create Date: 2026-07-22 16:37:29.388993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5282c6f66bde'
down_revision: Union[str, Sequence[str], None] = 'c21465661c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_details', sa.Column('summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_details', 'summary')
    # ### end Alembic commands ###
