"""add media_path in media_details table

Revision ID: bb208b028778
Revises: 234dd525338f
Create Date: 2026-07-22 17:25:07.117130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb208b028778'
down_revision: Union[str, Sequence[str], None] = '234dd525338f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_details', sa.Column('media_path', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'media_details', ['media_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_details', type_='unique')
    op.drop_column('media_details', 'media_path')
    # ### end Alembic commands ###
