"""Create Media and Media_Details tables

Revision ID: c21465661c33
Revises: 
Create Date: 2026-07-22 16:10:35.181742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21465661c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('media_name', sa.String(), nullable=False),
    sa.Column('media_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_details_media_id'), 'media_details', ['media_id'], unique=True)
    op.create_index(op.f('ix_media_details_media_name'), 'media_details', ['media_name'], unique=True)
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_name', sa.String(), nullable=False),
    sa.Column('media', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medias_media_name'), 'medias', ['media_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medias_media_name'), table_name='medias')
    op.drop_table('medias')
    op.drop_index(op.f('ix_media_details_media_name'), table_name='media_details')
    op.drop_index(op.f('ix_media_details_media_id'), table_name='media_details')
    op.drop_table('media_details')
    # ### end Alembic commands ###
